#ifndef __QTINCLUDE_H
#define __QTINCLUDE_H

#include <QAction>
#include <QApplication>
#include <QCheckBox>
#include <QComboBox>
#include <QDateTime>
#include <QDialog>
#include <QDialogButtonBox>
#include <QEvent>
#include <QFrame>
#include <QGridLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QIcon>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QPushButton>
#include <QRadioButton>
#include <QSerialPort>
#include <QSerialPortInfo>
#include <QSize>
#include <QStyleFactory>
#include <QTabWidget>
#include <QTextEdit>
#include <QTextCursor>
#include <QTextBlock>
#include <QTimer>
#include <QToolBar>
#include <QToolButton>
#include <QTranslator>
#include <QStyle>
#include <QVBoxLayout>
#include <QWidget>
#include "qtermwidget.h"
#include "TerminalDisplay.h"

#endif
