name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
  
env:
  APP_NAME: "ly-serial-tool"
  BUILD_TYPE: Release
  QT_VERSION: 6.9.2

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
      short_hash: ${{ steps.read_version.outputs.short_hash }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read version from file
      id: read_version
      run: |
        if [ "${{ github.ref_type }}" == "tag" ]; then
          VERSION=${{ github.ref_name }}
          SHORT_HASH=""
        else 
          MAJOR_MINOR=$(cut -d. -f1-2 VERSION)
          VERSION="${MAJOR_MINOR}.99"
          # Get the short hash of the current commit
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          SHORT_HASH="-$COMMIT_HASH"
        fi
        
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        echo "SHORT_HASH=$SHORT_HASH" >> $GITHUB_ENV
        echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT
        
    - name: Print version and hash
      run: |
        echo "ly-serial-tool version is ${{ env.VERSION }}"
        echo "ly-serial-tool short hash is ${{ env.SHORT_HASH }}"
      
  build-linux-appimage:
    runs-on: ${{ matrix.config.os }}
    continue-on-error: true
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            platform_tag: x86_64                 
          - os: ubuntu-24.04-arm
            platform_tag: aarch64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set version environment variable
      run: |
        echo "VERSION=${{ needs.setup.outputs.version }}" >> $GITHUB_ENV
        echo "SHORT_HASH=${{ needs.setup.outputs.short_hash }}" >> $GITHUB_ENV

    - name: Print version and hash
      run: |
        echo "ly-serial-tool version is ${{ env.VERSION }}"
        echo "ly-serial-tool short hash is ${{ env.SHORT_HASH }}"

    - name: Install Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake ninja-build

    - name: 'Install Qt6'
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{env.QT_VERSION}}
        host: ${{ matrix.config.platform_tag == 'aarch64' && 'linux_arm64' || 'linux' }}
        target: 'desktop'
        cache: true
        install-deps: 'true'
        modules: 'qtserialport'

    - name: 'Configure CMake'
      run: |
          cmake -B ${{github.workspace}}/build -G 'Ninja' \
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/AppDir/usr

    - name: 'Build'
      # Build your program with the given configuration
      run: |
          cmake --build ${{github.workspace}}/build -j`nproc` --config ${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --target install

      
    - name: 'Install linuxdeploy'
      run: |
          wget -q --tries=3 --wait=5 \
                https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${{ matrix.config.platform_tag }}.AppImage
          wget -q --tries=3 --wait=5 \
                https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-${{ matrix.config.platform_tag }}.AppImage
          sudo apt-get install fuse libfuse2
          chmod +x linuxdeploy-${{ matrix.config.platform_tag }}.AppImage
          chmod +x linuxdeploy-plugin-qt-${{ matrix.config.platform_tag }}.AppImage
    
    - name: 'Create AppImage'
      run: |
          ./linuxdeploy-${{ matrix.config.platform_tag }}.AppImage --appdir ${{github.workspace}}/AppDir \
                                        --desktop-file=${{github.workspace}}/AppDir/usr/share/applications/ly-serial-tool.desktop \
                                        --icon-file=${{github.workspace}}/AppDir/usr/share/icons/hicolor/256x256/apps/ly-serial-tool.png \
                                        --plugin=qt --output appimage
          rm linuxdeploy-${{ matrix.config.platform_tag }}.AppImage
          rm linuxdeploy-plugin-qt-${{ matrix.config.platform_tag }}.AppImage
          mv *.AppImage ${{ env.APP_NAME }}-${{env.VERSION}}${{env.SHORT_HASH}}-linux-${{ matrix.config.platform_tag }}.AppImage

    - name: 'Upload artifact: AppImage'
      uses: actions/upload-artifact@v4
      with:
          name: ${{ env.APP_NAME }}-${{env.VERSION}}${{env.SHORT_HASH}}-linux-${{ matrix.config.platform_tag }}
          path: ${{ env.APP_NAME }}-${{env.VERSION}}${{env.SHORT_HASH}}-linux-${{ matrix.config.platform_tag }}.AppImage

  create-release:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: [setup, build-linux-appimage]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set version environment variable
      run: |
        echo "VERSION=${{ needs.setup.outputs.version }}" >> $GITHUB_ENV
        echo "SHORT_HASH=${{ needs.setup.outputs.short_hash }}" >> $GITHUB_ENV

    - name: Print version and hash
      run: |
        echo "ly-serial-tool version is ${{ env.VERSION }}"
        echo "ly-serial-tool short hash is ${{ env.SHORT_HASH }}"

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ~/artifacts
        merge-multiple: true

    - name: Calculate SHA-256 checksums
      run: |
        cd ~/artifacts
        > hashes.sha256
        for file in $(find . -type f \(-name "*.AppImage" \)); do
          filename=$(basename "$file")
          sha256sum "$file" | awk -v fname="$filename" '{print $1 " *" fname}' >> hashes.sha256
        done
        cd ..
        tree ~/artifacts

    - name: Setup Release Information
      run: |
        if [ "${{github.ref_type}}" == "tag" ]; then
          echo "PRERELEASE=" >> $GITHUB_ENV
          echo "RELEASE_NAME=ly-serial-tool ${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_NOTES=--generate-notes" >> $GITHUB_ENV
        else
          echo "PRERELEASE=-p" >> $GITHUB_ENV
          echo "RELEASE_NAME=Continuous Build" >> $GITHUB_ENV
          echo "TAG_NAME=continuous_build" >> $GITHUB_ENV
          echo "RELEASE_NOTES=--notes \"Automated release for commit ${{ github.sha }}\"" >> $GITHUB_ENV
        fi
          
    - name: Create GitHub Release
      continue-on-error: false
      run: |
        # Find existing artifact files
        appimage_files=$(find ~/artifacts -name "*.AppImage" -print0 | xargs -0 echo)

        # Check existing release and delete if it's exist
        if gh release view ${{ env.TAG_NAME }} --repo $GITHUB_REPOSITORY &> /dev/null; then
          if [ "${{ env.TAG_NAME }}" == "continuous_build" ]; then
            gh release delete ${{ env.TAG_NAME }} --repo $GITHUB_REPOSITORY --cleanup-tag  --yes
          else
            gh release delete ${{ env.TAG_NAME }} --repo $GITHUB_REPOSITORY
          fi
          echo "${{ env.TAG_NAME }} deleted!"
        fi
        
        if [ -n "$appimage_files" ]; then
          gh release create ${{ env.TAG_NAME }} \
                            $appimage_files \
                            ${{ env.PRERELEASE }} \
                            --repo $GITHUB_REPOSITORY \
                            --title "${{ env.RELEASE_NAME }}" \
                            ${{ env.RELEASE_NOTES }}

            echo "${{ env.TAG_NAME }} release created!"
        else
          echo "No artifacts to upload."
          exit 1
        fi
        
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
